// ============================================================
// PlanCraft AI — Unified Markdown File Exporter
// ============================================================

import type { Project } from "@/lib/types";

const TASK_CATEGORY_LABELS: Record<string, string> = {
  setup: "🔧 Setup & Configuration",
  database: "🗄️ Database",
  backend: "⚙️ Backend",
  frontend: "🎨 Frontend",
  testing: "🧪 Testing",
  deployment: "🚀 Deployment",
};

export function compileProjectMarkdown(project: Project): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${project.title || "Untitled Project"} — Project Specification`);
  sections.push("");
  sections.push(`> Generated by PlanCraft AI on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  sections.push("");
  sections.push("---");
  sections.push("");

  // Vision & Overview
  sections.push("## 📋 Vision & Overview");
  sections.push("");
  sections.push(project.rawIdea || "_No idea provided._");
  sections.push("");

  // Clarified Scope
  if (project.clarifyingQuestions.length > 0) {
    sections.push("### Clarified Scope");
    sections.push("");
    project.clarifyingQuestions.forEach((qa, i) => {
      sections.push(`**Q${i + 1}:** ${qa.question}`);
      sections.push(`**A${i + 1}:** ${qa.answer}`);
      sections.push("");
    });
  }

  sections.push("---");
  sections.push("");

  // Tech Stack
  if (project.systemStructure) {
    const s = project.systemStructure;
    sections.push("## 🛠️ Recommended Tech Stack");
    sections.push("");
    sections.push(`**Scale:** ${s.scale}`);
    sections.push("");
    sections.push(`**Overview:** ${s.overview}`);
    sections.push("");
    sections.push("| Layer | Technology |");
    sections.push("|-------|-----------|");
    sections.push(`| Frontend | ${s.techStack.frontend} |`);
    sections.push(`| Backend | ${s.techStack.backend} |`);
    sections.push(`| Database | ${s.techStack.database} |`);
    sections.push(`| Deployment | ${s.techStack.deployment} |`);
    if (s.techStack.extras.length > 0) {
      sections.push(`| Extras | ${s.techStack.extras.join(", ")} |`);
    }
    sections.push("");

    sections.push("### Core Features");
    sections.push("");
    s.coreFeatures.forEach((f) => sections.push(`- ${f}`));
    sections.push("");

    sections.push("### Architecture");
    sections.push("");
    sections.push(s.architecture);
    sections.push("");

    sections.push("---");
    sections.push("");
  }

  // PRD
  if (project.prdContent) {
    sections.push("## 📄 Product Requirements Document");
    sections.push("");
    sections.push(project.prdContent);
    sections.push("");
    sections.push("---");
    sections.push("");
  }

  // Task Breakdown
  if (project.tasks.length > 0) {
    sections.push("## ✅ Development Task Breakdown");
    sections.push("");

    // Group tasks by category
    const grouped = project.tasks.reduce(
      (acc, task) => {
        const cat = task.category;
        if (!acc[cat]) acc[cat] = [];
        acc[cat].push(task);
        return acc;
      },
      {} as Record<string, typeof project.tasks>
    );

    const categoryOrder = [
      "setup",
      "database",
      "backend",
      "frontend",
      "testing",
      "deployment",
    ];

    categoryOrder.forEach((cat) => {
      const tasks = grouped[cat];
      if (!tasks || tasks.length === 0) return;
      sections.push(`### ${TASK_CATEGORY_LABELS[cat] || cat}`);
      sections.push("");
      tasks.forEach((task) => {
        const check = task.completed ? "x" : " ";
        sections.push(`- [${check}] **${task.title}**`);
        if (task.description) {
          sections.push(`  ${task.description}`);
        }
      });
      sections.push("");
    });
  }

  sections.push("---");
  sections.push("");
  sections.push("*This specification was generated by [PlanCraft AI](https://plancrafter.vercel.app) — Transform ideas into developer-ready PRDs.*");

  return sections.join("\n");
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = text;
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand("copy");
    document.body.removeChild(textarea);
    return success;
  }
}
